const inputDetails = [
  {
    type: "text",
    placeholder: "Enter Name",
    name: "name",
    id: "name",
    title: "Name",
  },
  {
    type: "email",
    placeholder: "Enter Email",
    name: "email",
    id: "email",
    title: "Email",
  },
  {
    type: "number",
    placeholder: "Enter Phone No",
    name: "phone",
    id: "phone",
    title: "Phone No",
  },
  {
    type: "text",
    placeholder: "Enter Student ID",
    name: "studentId",
    id: "studentId",
    title: "Student ID",
  },
  {
    type: "text",
    placeholder: "Enter LearnCab ID",
    name: "learncabId",
    id: "learncabId",
    title: "LearnCab ID",
  },
  {
    type: "text",
    placeholder: "Enter Address",
    name: "address",
    id: "address",
    title: "Address",
  },
  {
    type: "text",
    placeholder: "Enter City",
    name: "city",
    id: "city",
    title: "City",
  },
  {
    type: "text",
    placeholder: "Enter State",
    name: "state",
    id: "state",
    title: "State",
  },
  {
    type: "text",
    placeholder: "Enter Pincode",
    name: "pincode",
    id: "pincode",
    title: "Pincode",
  },
  {
    type: "text",
    placeholder: "Enter Country",
    name: "country",
    id: "country",
    title: "Country",
  },
  {
    type: "text",
    placeholder: "Enter GST Number",
    name: "gstNo",
    id: "gstNo",
    title: "GST Number",
  },
  {
    type: "text",
    placeholder: "Enter Payment ID",
    name: "paymentId",
    id: "paymentId",
    title: "Payment ID",
  },
];

export default inputDetails;
